fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
    logrotate:
      repo: git://github.com/voxpupuli/puppet-logrotate.git
  symlinks:
    psacct: "#{source_dir}"
